#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore

bspc monitor -d 1 2 3 4 5

bspc config border_width 4
bspc config window_gap 12
bspc config normal_border_color "#957FB8"
bspc config focused_border_color "#938AA9"
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a alacritty desktop='^1' state=tiled follow=on
bspc rule -a firefox desktop='^2' state=tiled follow=on
bspc rule -a spotify desktop='^3' state=tiled follow=on
bspc rule -a discord desktop='^4' state=tiled follow=on
bspc rule -a zathura desktop='^5' state=tiled follow=on
bspc rule -a Lxappearance state=floating follow=on

# Touchpad set up
xinput set-prop 10 "libinput Natural Scrolling Enabled" 1 # Natural scrolling
xinput set-prop 10 "libinput Tapping Enabled" 1 # Tapping to click

picom &
sh $HOME/.config/polybar/launch.sh & #Polybar
dunst &
